# mybatisGenerator 配置文件
mybatisGenerator:
  datasource:
    type: mysql
    address: localhost:3306
    db: product?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  targetPackage:
    ## 生成 domain 和 mapper 路径
    model: com.micro.mall.product.model
    mapper: com.micro.mall.product.mapper
    javaXmlFilesSamePackage: false

  targetRuntime: MyBatis3
  mapperSuffixName: mapper
  java8: false
  disableExample: false
  ## 插件支持
  plugins:
    comment: true
    lombok: true
    swagger: true
    mapperAnnotation: false
    serializable: false

  # 需要生成的表
  tables:
    - category
    - brand
    - product
    - product_property_value
    - property
    - sku_stock
    - type