server:
  port: 8402
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

redis:
  host: localhost # Redis服务器地址
  port: 6379 # Redis服务器连接端口
  password:  # Redis服务器连接密码（默认为空）
  timeout: 3000ms # 连接超时时间（毫秒）
  database: mall
  key: 'mall:user'
  expire:
    common: 86400 # 24小时

# mybatis-mapper 扫描路径
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml